pub mod ast;
pub mod audit;
pub mod batches;
pub mod chemistry;
pub mod comparison;
pub mod compiler;
pub mod constants;
pub mod custody;
pub mod delimited;
pub mod electrical;
pub mod error;
pub mod evaluator;
pub mod fits;
pub mod hashing;
pub mod inference_policy;
pub mod inline_rust;
pub mod interaction;
pub mod ledger;
pub mod lexer;
pub mod math_policy;
pub mod matrix;
pub mod modules;
pub mod numeric_comparison;
pub mod output;
pub mod parser;
pub mod quantity;
pub mod random;
pub mod resampling;
pub mod resources;
pub mod runtime;
pub mod science;
mod statistics_runtime;
pub mod streaming;
pub mod text_runtime;

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
